// 66-book canon: [number, Slovak name, English name, biblia.sk abbreviation]
const BIBLE_BOOKS = [
  [1,"Genezis","Genesis","gn"],
  [2,"Exodus","Exodus","ex"],
  [3,"Levitikus","Leviticus","lv"],
  [4,"Numeri","Numbers","nm"],
  [5,"Deuteronómium","Deuteronomy","dt"],
  [6,"Jozua","Joshua","joz"],
  [7,"Sudcovia","Judges","sdc"],
  [8,"Rút","Ruth","rut"],
  [9,"1. Samuelova","1 Samuel","1sam"],
  [10,"2. Samuelova","2 Samuel","2sam"],
  [11,"1. Kráľov","1 Kings","1krl"],
  [12,"2. Kráľov","2 Kings","2krl"],
  [13,"1. Kroník","1 Chronicles","1krn"],
  [14,"2. Kroník","2 Chronicles","2krn"],
  [15,"Ezdráš","Ezra","ezd"],
  [16,"Nehemiáš","Nehemiah","neh"],
  [17,"Ester","Esther","est"],
  [18,"Jób","Job","job"],
  [19,"Žalmy","Psalms","z"],
  [20,"Príslovia","Proverbs","pris"],
  [21,"Kazateľ","Ecclesiastes","koh"],
  [22,"Pieseň piesní","Song of Solomon","vlp"],
  [23,"Izaiáš","Isaiah","iz"],
  [24,"Jeremiáš","Jeremiah","jer"],
  [25,"Náreky","Lamentations","nar"],
  [26,"Ezechiel","Ezekiel","ez"],
  [27,"Daniel","Daniel","dan"],
  [28,"Ozeáš","Hosea","oz"],
  [29,"Joel","Joel","joel"],
  [30,"Ámos","Amos","am"],
  [31,"Abdiáš","Obadiah","abd"],
  [32,"Jonáš","Jonah","jon"],
  [33,"Micheáš","Micah","mich"],
  [34,"Nahum","Nahum","nah"],
  [35,"Habakuk","Habakkuk","hab"],
  [36,"Sofoniáš","Zephaniah","sof"],
  [37,"Aggeus","Haggai","ag"],
  [38,"Zachariáš","Zechariah","zach"],
  [39,"Malachiáš","Malachi","mal"],
  [40,"Matúš","Matthew","mt"],
  [41,"Marek","Mark","mk"],
  [42,"Lukáš","Luke","lk"],
  [43,"Ján","John","jn"],
  [44,"Skutky","Acts","sk"],
  [45,"Rimanom","Romans","rim"],
  [46,"1. Korinťanom","1 Corinthians","1kor"],
  [47,"2. Korinťanom","2 Corinthians","2kor"],
  [48,"Galaťanom","Galatians","ga"],
  [49,"Efezanom","Ephesians","ef"],
  [50,"Filipanom","Philippians","flp"],
  [51,"Kolosanom","Colossians","kol"],
  [52,"1. Tesaloničanom","1 Thessalonians","1tes"],
  [53,"2. Tesaloničanom","2 Thessalonians","2tes"],
  [54,"1. Timotejovi","1 Timothy","1tim"],
  [55,"2. Timotejovi","2 Timothy","2tim"],
  [56,"Títovi","Titus","tit"],
  [57,"Filemonovi","Philemon","flm"],
  [58,"Hebrejom","Hebrews","heb"],
  [59,"Jakubov","James","jk"],
  [60,"1. Petrov","1 Peter","1pt"],
  [61,"2. Petrov","2 Peter","2pt"],
  [62,"1. Jánov","1 John","1jn"],
  [63,"2. Jánov","2 John","2jn"],
  [64,"3. Jánov","3 John","3jn"],
  [65,"Júdov","Jude","jud"],
  [66,"Zjavenie","Revelation","zj"]
];

// [code, Slovak label, short badge, English label]
const BIBLE_TRANS = [
  ["seb", "Ekumenický", "SEB", "Slovak Ecumenical"],
  ["ssv", "Katolícky", "SSV", "Slovak Catholic"],
  ["roh", "Roháček", "ROH", "Roháček (1936)"],
  ["kjv", "King James", "KJV", "King James Version"]
];

const OT_COUNT = 39; // books 1..39 are the Old Testament

// Chapter count per book (SEB versification) — for reading plans.
const SEB_CHAPTERS = [50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,4,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,22];
