// Prophecies data: [OT reference, prophecy EN, prophecy SK, NT fulfilment]
const PROPHECIES_DATA = [
["Genesis", [
["Genesis 3:15","Seed of a woman — the virgin birth","Potomstvo ženy — narodenie z panny","Galatians 4:4–5; Matthew 1:18"],
["Genesis 3:15","He will bruise Satan's head","Rozšliape satanovi hlavu","Hebrews 2:14; 1 John 3:8"],
["Genesis 5:24","The bodily ascension to heaven illustrated","Telesné nanebovstúpenie predobrazené","Mark 16:19"],
["Genesis 9:26–27","The God of Shem will be the Son of Shem","Boh Sema bude Semovým synom","Luke 3:36"],
["Genesis 12:3","Seed of Abraham will bless all nations","Abrahámovo potomstvo požehná všetky národy","Galatians 3:8; Acts 3:25–26"],
["Genesis 12:7","The Promise made to Abraham's Seed","Prisľúbenie dané Abrahámovmu potomkovi","Galatians 3:16"],
["Genesis 14:18","A priest after the order of Melchizedek","Kňaz podľa radu Melchizedecha","Hebrews 6:20"],
["Genesis 14:18","King of Peace and Righteousness","Kráľ pokoja a spravodlivosti","Hebrews 7:2"],
["Genesis 14:18","The Last Supper foreshadowed","Predobraz Poslednej večere","Matthew 26:26–29"],
["Genesis 17:19","Seed of Isaac","Potomok Izáka","Romans 9:7"],
["Genesis 21:12","Seed of Isaac","Potomok Izáka","Romans 9:7; Hebrews 11:18"],
["Genesis 22:8","The Lamb of God promised","Prisľúbený Boží Baránok","John 1:29"],
["Genesis 22:18","As Isaac's seed, will bless all nations","Ako Izákov potomok požehná všetky národy","Galatians 3:16"],
["Genesis 26:2–5","The Seed of Isaac promised as the Redeemer","Izákov potomok prisľúbený ako Vykupiteľ","Hebrews 11:18"],
["Genesis 28:12","The Bridge to heaven","Most do neba — Jakubov rebrík","John 1:51"],
["Genesis 28:14","The Seed of Jacob","Potomok Jakuba","Luke 3:34"],
["Genesis 49:10","The time of His coming","Čas jeho príchodu","Luke 2:1–7; Galatians 4:4"],
["Genesis 49:10","The Seed of Judah","Potomok Júdu","Luke 3:33"],
["Genesis 49:10","Called Shiloh — One Sent","Nazvaný Šílo — Poslaný","John 17:3"],
["Genesis 49:10","To come before Judah lost its identity","Príde skôr, než Júda stratí svoju identitu","John 11:47–52"],
["Genesis 49:10","Unto Him shall the obedience of the people be","Jemu bude patriť poslušnosť národov","John 10:16"]
]],
["Exodus", [
["Exodus 3:13–15","The Great I AM","Veľký JA SOM","John 4:26; 8:58"],
["Exodus 12:5","A Lamb without blemish","Baránok bez chyby","Hebrews 9:14; 1 Peter 1:19"],
["Exodus 12:13","The blood of the Lamb saves from wrath","Krv Baránka zachraňuje pred hnevom","Romans 5:8"],
["Exodus 12:21–27","Christ is our Passover","Kristus je náš veľkonočný Baránok","1 Corinthians 5:7"],
["Exodus 12:46","Not a bone of the Lamb to be broken","Baránkovi nebude zlomená ani kosť","John 19:31–36"],
["Exodus 15:2","His exaltation predicted as Yeshua","Jeho vyvýšenie predpovedané ako Ješua","Acts 7:55–56"],
["Exodus 15:11","His character — holiness","Jeho povaha — svätosť","Luke 1:35; Acts 4:27"],
["Exodus 17:6","The spiritual Rock of Israel","Duchovná Skala Izraela","1 Corinthians 10:4"],
["Exodus 33:19","His character — merciful","Jeho povaha — milosrdný","Luke 1:72"]
]],
["Leviticus", [
["Leviticus 1:2–9","His sacrifice a sweet-smelling savour unto God","Jeho obeta — príjemná vôňa Bohu","Ephesians 5:2"],
["Leviticus 14:11","The leper cleansed — sign to the priesthood","Očistený malomocný — znamenie kňazstvu","Luke 5:12–14; Acts 6:7"],
["Leviticus 16:15–17","Prefigures Christ's once-for-all death","Predobraz Kristovej smrti raz a navždy","Hebrews 9:7–14"],
["Leviticus 16:27","Suffering outside the camp","Utrpenie za táborom","Matthew 27:33; Hebrews 13:11–12"],
["Leviticus 17:11","The blood — the life of the flesh","Krv — život tela","Matthew 26:28; Mark 10:45"],
["Leviticus 17:11","It is the blood that makes atonement","Krv je to, čo zmieruje","Romans 3:23–24; 1 John 1:7"],
["Leviticus 23:36–37","The drink-offering: “if any man thirst”","Obeta nápoja: „ak je niekto smädný…“","John 7:37"]
]],
["Numbers", [
["Numbers 9:12","Not a bone of Him broken","Nebude mu zlomená ani kosť","John 19:31–36"],
["Numbers 21:9","The serpent on a pole — Christ lifted up","Had na žrdi — Kristus vyzdvihnutý","John 3:14–18; 12:32"],
["Numbers 24:17","Time: “I shall see him, but not now.”","Čas: „Vidím ho, ale nie teraz.“","John 1:14; Galatians 4:4"]
]],
["Deuteronomy", [
["Deuteronomy 18:15","“This is of a truth that prophet.”","„Toto je naozaj ten prorok.“","John 6:14"],
["Deuteronomy 18:15–16","“Had ye believed Moses, ye would believe me.”","„Keby ste verili Mojžišovi, verili by ste mne.“","John 5:45–47"],
["Deuteronomy 18:18","Sent by the Father to speak His word","Poslaný Otcom hovoriť jeho slovo","John 8:28–29"],
["Deuteronomy 18:19","Whoever will not hear must bear his sin","Kto nepočúvne, ponesie svoj hriech","Acts 3:22–23"],
["Deuteronomy 21:23","Cursed is he that hangs on a tree","Prekliaty, kto visí na dreve","Galatians 3:10–13"]
]],
["Ruth & Samuel", [
["Ruth 4:4–10","Christ, our kinsman, has redeemed us","Kristus, náš príbuzný, nás vykúpil","Ephesians 1:3–7"],
["1 Samuel 2:35","A faithful Priest","Verný kňaz","Hebrews 2:17; 3:1–3; 7:24–25"],
["2 Samuel 7:12","David's Seed","Potomok Dávida","Matthew 1:1"],
["2 Samuel 7:13","His kingdom is everlasting","Jeho kráľovstvo je večné","2 Peter 1:11"],
["2 Samuel 7:14","The Son of God","Boží Syn","Luke 1:32; Romans 1:3–4"],
["2 Samuel 7:16","David's house established forever","Dávidov dom upevnený naveky","Luke 3:31; Revelation 22:16"]
]],
["Kings & Chronicles", [
["2 Kings 2:11","The bodily ascension to heaven illustrated","Telesné nanebovstúpenie predobrazené","Luke 24:51"],
["1 Chronicles 17:11","David's Seed","Potomok Dávida","Matthew 1:1; 9:27"],
["1 Chronicles 17:12–13","To reign on David's throne forever","Bude naveky kraľovať na Dávidovom tróne","Luke 1:32–33"],
["1 Chronicles 17:13","“I will be His Father, He … my Son.”","„Ja mu budem Otcom a on mi bude Synom.“","Hebrews 1:5"]
]],
["Job", [
["Job 9:32–33","Mediator between man and God","Prostredník medzi človekom a Bohom","1 Timothy 2:5"],
["Job 19:23–27","The Resurrection predicted","Predpovedané vzkriesenie","John 5:24–29"]
]],
["Psalms", [
["Psalm 2:1–3","The enmity of kings foreordained","Nepriateľstvo kráľov vopred určené","Acts 4:25–28"],
["Psalm 2:2","To own the title Anointed (Christ)","Ponesie titul Pomazaný — Kristus","John 1:41; Acts 2:36"],
["Psalm 2:6","His character — holiness","Jeho povaha — svätosť","John 8:46; Revelation 3:7"],
["Psalm 2:6","To own the title King","Ponesie titul Kráľ","Matthew 2:2"],
["Psalm 2:7","Declared the beloved Son","Vyhlásený za milovaného Syna","Matthew 3:17; Romans 1:4"],
["Psalm 2:7–8","The crucifixion and resurrection intimated","Naznačené ukrižovanie a vzkriesenie","Acts 13:29–33"],
["Psalm 2:8–9","To rule the nations with a rod of iron","Bude vládnuť národom železným žezlom","Revelation 2:27; 12:5; 19:15"],
["Psalm 2:12","Life comes through faith in Him","Život prichádza vierou v neho","John 20:31"],
["Psalm 8:2","The mouths of babes perfect His praise","Z úst detí zaznieva jeho chvála","Matthew 21:16"],
["Psalm 8:5–6","His humiliation and exaltation","Jeho poníženie a vyvýšenie","Hebrews 2:5–9"],
["Psalm 9:7–10","To judge the world in righteousness","Bude súdiť svet v spravodlivosti","Acts 17:31"],
["Psalm 16:10","Was not to see corruption","Neuvidí porušenie","Acts 2:31; 13:35"],
["Psalm 16:9–11","Was to arise from the dead","Vstane z mŕtvych","John 20:9"],
["Psalm 17:15","The resurrection predicted","Predpovedané vzkriesenie","Luke 24:6"],
["Psalm 18:2–3","The horn of salvation","Roh spásy","Luke 1:69–71"],
["Psalm 22:1","Forsaken because of the sins of others","Opustený pre hriechy iných","2 Corinthians 5:21"],
["Psalm 22:1","“My God, my God, why hast thou forsaken me?”","„Bože môj, Bože môj, prečo si ma opustil?“","Matthew 27:46"],
["Psalm 22:2","Darkness upon Calvary for three hours","Tma nad Golgotou tri hodiny","Matthew 27:45"],
["Psalm 22:7","They shoot out the lip and shake the head","Vyškierajú sa a potriasajú hlavou","Matthew 27:39–44"],
["Psalm 22:8","“He trusted in God, let Him deliver Him.”","„Dúfal v Boha, nech ho vyslobodí.“","Matthew 27:43"],
["Psalm 22:9–10","Born the Saviour","Narodený ako Spasiteľ","Luke 2:7"],
["Psalm 22:12–13","They seek His death","Usilujú o jeho smrť","John 19:6"],
["Psalm 22:14","His blood poured out when His side was pierced","Jeho krv vyliata pri prebodnutí boku","John 19:34"],
["Psalm 22:14–15","Suffered agony on Calvary","Trpel muky na Golgote","Mark 15:34–37"],
["Psalm 22:15","He thirsted","Bol smädný","John 19:28"],
["Psalm 22:16","They pierced His hands and His feet","Prebodli mu ruky a nohy","John 19:34–37; 20:27"],
["Psalm 22:17–18","Stripped Him before the stares of men","Vyzliekli ho pred očami ľudí","Luke 23:34–35"],
["Psalm 22:18","They parted His garments and cast lots","Rozdelili si jeho rúcho a hádzali lós","John 19:23–24"],
["Psalm 22:20–21","He committed Himself to God","Odovzdal sa Bohu","Luke 23:46"],
["Psalm 22:20–21","Satanic power bruising the Redeemer's heel","Satan raní Vykupiteľovu pätu","Hebrews 2:14"],
["Psalm 22:22","His resurrection declared","Ohlásené jeho vzkriesenie","John 20:17"],
["Psalm 22:27–28","He shall be the governor of the nations","Bude vládcom národov","Colossians 1:16"],
["Psalm 22:31","“It is finished.”","„Je dokonané.“","John 19:30; Hebrews 10:10–18"],
["Psalm 23:1","“I am the Good Shepherd.”","„Ja som dobrý pastier.“","John 10:11; 1 Peter 2:25"],
["Psalm 24:3","His exaltation predicted","Predpovedané jeho vyvýšenie","Acts 1:11; Philippians 2:9"],
["Psalm 27:12","False witnesses rise up against Him","Povstávajú proti nemu falošní svedkovia","Matthew 26:60–61"],
["Psalm 30:3","His resurrection predicted","Predpovedané jeho vzkriesenie","Acts 2:32"],
["Psalm 31:5","“Into thy hands I commit my spirit.”","„Do tvojich rúk porúčam svojho ducha.“","Luke 23:46"],
["Psalm 31:11","His acquaintances fled from Him","Jeho známi od neho utiekli","Mark 14:50"],
["Psalm 31:13","They took counsel to put Him to death","Radili sa, ako ho usmrtiť","Matthew 27:1; John 11:53"],
["Psalm 31:14–15","“He trusted in God, let Him deliver him.”","„Dúfal v Boha, nech ho vyslobodí.“","Matthew 27:43"],
["Psalm 34:20","Not a bone of Him broken","Nebude mu zlomená ani kosť","John 19:31–36"],
["Psalm 35:11","False witnesses rose up against Him","Povstali proti nemu falošní svedkovia","Matthew 26:59–61"],
["Psalm 35:19","He was hated without a cause","Nenávideli ho bez príčiny","John 15:25"],
["Psalm 38:11","His friends stood afar off","Jeho priatelia stáli obďaleč","Luke 23:49"],
["Psalm 38:12","Enemies tried to entangle Him by craft","Nepriatelia ho chceli chytiť ľsťou","Mark 14:1; Matthew 22:15"],
["Psalm 38:12–13","Silent before His accusers","Mlčal pred žalobcami","Matthew 27:12–14"],
["Psalm 38:20","He went about doing good","Chodil a dobre robil","Acts 10:38"],
["Psalm 40:2–5","The joy of His resurrection predicted","Predpovedaná radosť jeho vzkriesenia","John 20:20"],
["Psalm 40:6–8","His delight — the will of the Father","Jeho záľuba — Otcova vôľa","John 4:34; Hebrews 10:5–10"],
["Psalm 40:9","He was to preach righteousness in Israel","Bude hlásať spravodlivosť v Izraeli","Matthew 4:17"],
["Psalm 40:14","Confronted by adversaries in the garden","Konfrontovaný protivníkmi v záhrade","John 18:4–6"],
["Psalm 41:9","Betrayed by a familiar friend","Zradený dôverným priateľom","John 13:18"],
["Psalm 45:2","Words of grace come from His lips","Z jeho perí plynú slová milosti","John 1:17; Luke 4:22"],
["Psalm 45:6","To own the title God (Elohim)","Ponesie titul Boh — Elohim","Hebrews 1:8"],
["Psalm 45:7","A special anointing by the Holy Spirit","Osobitné pomazanie Duchom Svätým","Matthew 3:16; Hebrews 1:9"],
["Psalm 45:7–8","Called the Christ — Messiah, Anointed","Nazvaný Kristus — Mesiáš, Pomazaný","Luke 2:11"],
["Psalm 45:17","His name remembered forever","Jeho meno bude pripomínané naveky","Ephesians 1:20–21; Hebrews 1:8"],
["Psalm 55:12–14","Betrayed by a friend, not an enemy","Zradený priateľom, nie nepriateľom","John 13:18"],
["Psalm 55:15","Unrepentant death of the betrayer","Zradcova smrť bez pokánia","Matthew 27:3–5; Acts 1:16–19"],
["Psalm 68:18","To give gifts to men","Dá ľuďom dary","Ephesians 4:7–16"],
["Psalm 68:18","Ascended into heaven","Vystúpil do neba","Luke 24:51"],
["Psalm 69:4","Hated without a cause","Nenávidený bez príčiny","John 15:25"],
["Psalm 69:8","A stranger to His own brethren","Cudzí vlastným bratom","John 1:11; 7:5"],
["Psalm 69:9","Zealous for the Lord's house","Horlivosť za Pánov dom","John 2:17"],
["Psalm 69:14–20","Anguish of soul before the crucifixion","Úzkosť duše pred ukrižovaním","Matthew 26:36–45"],
["Psalm 69:20","“My soul is exceeding sorrowful.”","„Moja duša je smutná až na smrť.“","Matthew 26:38"],
["Psalm 69:21","Given vinegar in thirst","V smäde mu dali ocot","Matthew 27:34"],
["Psalm 69:26","The Saviour given and smitten by God","Spasiteľ daný a zbitý Bohom","John 17:4; 18:11"],
["Psalm 72:10–11","Great persons were to visit Him","Navštívia ho vznešení s darmi","Matthew 2:1–11"],
["Psalm 72:16","The corn of wheat to fall into the ground","Pšeničné zrno padne do zeme","John 12:24–25"],
["Psalm 72:17","Belief on His name produces offspring","Viera v jeho meno plodí potomstvo","John 1:12–13"],
["Psalm 72:17","All nations shall be blessed by Him","V ňom budú požehnané všetky národy","Galatians 3:8"],
["Psalm 72:17","All nations shall call Him blessed","Všetky národy ho budú blahoslaviť","John 12:13; Revelation 5:8–12"],
["Psalm 78:1–2","He would teach in parables","Bude učiť v podobenstvách","Matthew 13:34–35"],
["Psalm 78:2","To speak the wisdom of God with authority","Hovorí Božiu múdrosť s mocou","Matthew 7:29"],
["Psalm 80:17","The Man of God's right hand","Muž Božej pravice","Mark 14:61–62"],
["Psalm 88","The suffering and reproach of Calvary","Utrpenie a potupa Golgoty","Matthew 27:26–50"],
["Psalm 88:8","They stood afar off and watched","Stáli obďaleč a prizerali sa","Luke 23:49"],
["Psalm 89:26","Messiah will call God His Father","Mesiáš bude volať Boha svojím Otcom","Matthew 11:27"],
["Psalm 89:27","Emmanuel higher than earthly kings","Emanuel vyšší než pozemskí králi","Luke 1:32–33"],
["Psalm 89:35–37","David's Seed, throne and kingdom endure forever","Dávidovo potomstvo, trón a kráľovstvo naveky","Luke 1:32–33"],
["Psalm 90:2","He is from everlasting","Je od večnosti","John 1:1"],
["Psalm 91:11–12","Identified as Messianic — used to tempt Christ","Mesiášsky žalm — použitý pri pokúšaní Krista","Luke 4:10–11"],
["Psalm 97:9","His exaltation predicted","Predpovedané jeho vyvýšenie","Acts 1:11; Ephesians 1:20"],
["Psalm 100:5","His character — goodness","Jeho povaha — dobrota","Matthew 19:16–17"],
["Psalm 102:1–11","The suffering and reproach of Calvary","Utrpenie a potupa Golgoty","John 19:16–30"],
["Psalm 102:25–27","Messiah is the pre-existent Son","Mesiáš je Syn jestvujúci pred vekmi","Hebrews 1:10–12"],
["Psalm 109:4","Prays for His enemies","Modlí sa za svojich nepriateľov","Luke 23:34"],
["Psalm 109:7–8","Another to succeed Judas","Iný zaujme Judášov úrad","Acts 1:16–20"],
["Psalm 109:25","Ridiculed","Vysmievaný","Matthew 27:39"],
["Psalm 110:1","Son of David","Syn Dávidov","Matthew 22:41–45"],
["Psalm 110:1","To ascend to the right hand of the Father","Zasadne po pravici Otca","Mark 16:19"],
["Psalm 110:1","David's son called Lord","Dávidov syn nazvaný Pánom","Mark 12:35–37"],
["Psalm 110:4","A priest after Melchizedek's order","Kňaz podľa radu Melchizedecha","Hebrews 6:20"],
["Psalm 112:4","His character — compassionate, gracious","Jeho povaha — súcitný, milostivý","Matthew 9:36"],
["Psalm 118:17–18","Messiah's resurrection assured","Mesiášovo vzkriesenie zaistené","Luke 24:5–7; 1 Corinthians 15:20"],
["Psalm 118:22–23","The rejected stone is head of the corner","Zavrhnutý kameň sa stal uholným","Matthew 21:42–43"],
["Psalm 118:26","The Blessed One presented to Israel","Požehnaný predstavený Izraelu","Matthew 21:9"],
["Psalm 118:26","To come while the Temple was standing","Príde, kým ešte stojí chrám","Matthew 21:12–15"],
["Psalm 129:3","He was scourged","Bol zbičovaný","Matthew 27:26"],
["Psalm 132:11","The Seed of David — the fruit of His body","Potomok Dávida — plod jeho tela","Luke 1:32; Acts 2:30"],
["Psalm 138:1–6","The supremacy of David's Seed amazes kings","Zvrchovanosť Dávidovho potomka udivuje kráľov","Matthew 2:2–6"],
["Psalm 147:3–6","The earthly ministry of Christ described","Opísaná Kristova pozemská služba","Luke 4:18"]
]],
["Proverbs & Song of Solomon", [
["Proverbs 1:23","He will send the Spirit of God","Pošle Božieho Ducha","John 16:7"],
["Proverbs 8:23","Foreordained from everlasting","Ustanovený od večnosti","Revelation 13:8; 1 Peter 1:19–20"],
["Proverbs 30:4","Declared to be the Son of God","Vyhlásený za Božieho Syna","John 3:13; Romans 1:2–4; 2 Peter 1:17"],
["Song of Solomon 5:16","The altogether lovely One","Celý je pôvabný — najkrajší z ľudí","John 1:17"]
]],
["Isaiah", [
["Isaiah 2:3","He shall teach all nations","Bude učiť všetky národy","John 4:25"],
["Isaiah 2:4","He shall judge among the nations","Bude súdiť medzi národmi","John 5:22"],
["Isaiah 6:1","When Isaiah saw His glory","Izaiáš videl jeho slávu","John 12:40–41"],
["Isaiah 6:8","The One sent by God","Ten, ktorého poslal Boh","John 12:38–45"],
["Isaiah 6:9–10","Parables fall on deaf ears","Podobenstvá padajú na hluché uši","Matthew 13:13–15"],
["Isaiah 6:9–12","Blinded to Christ and deaf to His words","Slepí voči Kristovi, hluchí k jeho slovám","Acts 28:23–29"],
["Isaiah 7:14","To be born of a virgin","Narodí sa z panny","Luke 1:35"],
["Isaiah 7:14","To be Emmanuel — God with us","Bude Emanuel — Boh s nami","Matthew 1:18–23; 1 Timothy 3:16"],
["Isaiah 8:8","Called Emmanuel","Nazvaný Emanuel","Matthew 28:20"],
["Isaiah 8:14","A stone of stumbling, a rock of offence","Kameň úrazu a skala pohoršenia","1 Peter 2:8"],
["Isaiah 9:1–2","His ministry to begin in Galilee","Jeho služba sa začne v Galilei","Matthew 4:12–17"],
["Isaiah 9:6","A child born — His humanity","Dieťa sa narodilo — jeho ľudskosť","Luke 1:31"],
["Isaiah 9:6","A Son given — His deity","Syn je daný — jeho božstvo","Luke 1:32; John 1:14; 1 Timothy 3:16"],
["Isaiah 9:6","Declared the Son of God with power","Vyhlásený za Božieho Syna s mocou","Romans 1:3–4"],
["Isaiah 9:6","The Wonderful One — Peleh","Obdivuhodný — Peleh","Luke 4:22"],
["Isaiah 9:6","The Counsellor — Yaatz","Radca — Jaac","Matthew 13:54"],
["Isaiah 9:6","The Mighty God — El Gibbor","Mocný Boh — El Gibor","1 Corinthians 1:24; Titus 2:13"],
["Isaiah 9:6","The Everlasting Father — Avi Ad","Večný Otec — Avi Ad","John 8:58; 10:30"],
["Isaiah 9:6","The Prince of Peace — Sar Shalom","Knieža pokoja — Sar Šalom","John 16:33"],
["Isaiah 9:7","To establish an everlasting kingdom","Ustanoví večné kráľovstvo","Luke 1:32–33"],
["Isaiah 11:1","Called a Nazarene — the Branch, Netzer","Nazvaný Nazaretský — Výhonok, Necer","Matthew 2:23"],
["Isaiah 11:1","A rod out of Jesse — son of Jesse","Prút z kmeňa Izaiho — syn Izaiho","Luke 3:23–32"],
["Isaiah 11:2","Anointed One by the Spirit","Pomazaný Duchom","Matthew 3:16–17; Acts 10:38"],
["Isaiah 11:2","His character — wisdom, knowledge","Jeho povaha — múdrosť a poznanie","Colossians 2:3"],
["Isaiah 11:3","He would know their thoughts","Poznal ich myšlienky","Luke 6:8; John 2:25"],
["Isaiah 11:4","To judge in righteousness","Bude súdiť v spravodlivosti","Acts 17:31"],
["Isaiah 11:10","The Gentiles seek Him","Pohania ho hľadajú","John 12:18–21"],
["Isaiah 12:2","Called Jesus — Yeshua, salvation","Nazvaný Ježiš — Ješua, spása","Matthew 1:21"],
["Isaiah 22:22","The One given all authority to govern","Dostane všetku moc vládnuť","Revelation 3:7"],
["Isaiah 25:8","The resurrection predicted","Predpovedané vzkriesenie","1 Corinthians 15:54"],
["Isaiah 26:19","His power of resurrection predicted","Predpovedaná jeho moc vzkriesenia","Matthew 27:50–54"],
["Isaiah 28:16","The Messiah is the precious corner stone","Mesiáš je vzácny uholný kameň","Acts 4:11–12"],
["Isaiah 28:16","The sure foundation","Pevný základ","1 Corinthians 3:11; Matthew 16:18"],
["Isaiah 29:13","He indicated hypocritical obedience to His word","Odhalil pokryteckú poslušnosť jeho slovu","Matthew 15:7–9"],
["Isaiah 29:14","The wise are confounded by the Word","Múdri sú zahanbení Slovom","1 Corinthians 1:18–31"],
["Isaiah 32:2","A refuge — a man shall be a hiding place","Útočisko — človek bude skrýšou","Matthew 23:37"],
["Isaiah 35:4","He will come and save you","Príde a spasí vás","Matthew 1:21"],
["Isaiah 35:5–6","To have a ministry of miracles","Služba plná zázrakov","Matthew 11:2–6"],
["Isaiah 40:3–4","Preceded by a forerunner","Predchádzaný predchodcom","John 1:23"],
["Isaiah 40:9","“Behold your God.”","„Hľa, váš Boh.“","John 1:36; 19:14"],
["Isaiah 40:10","He will come to reward","Príde odmeniť","Revelation 22:12"],
["Isaiah 40:11","A shepherd — compassionate life-giver","Pastier — súcitný darca života","John 10:10–18"],
["Isaiah 42:1–4","The Servant — a faithful, patient redeemer","Služobník — verný a trpezlivý vykupiteľ","Matthew 12:18–21"],
["Isaiah 42:2","Meek and lowly","Tichý a pokorný","Matthew 11:28–30"],
["Isaiah 42:3","He brings hope for the hopeless","Prináša nádej beznádejným","John 4:1–26"],
["Isaiah 42:4","The nations shall wait on His teachings","Národy budú čakať na jeho učenie","John 12:20–26"],
["Isaiah 42:6","The Light (salvation) of the Gentiles","Svetlo a spása pohanov","Luke 2:32"],
["Isaiah 42:1, 6","His is a worldwide compassion","Jeho súcit patrí celému svetu","Matthew 28:19–20"],
["Isaiah 42:7","Blind eyes opened","Otvára slepé oči","John 9:25–38"],
["Isaiah 43:11","He is the only Saviour","Je jediný Spasiteľ","Acts 4:12"],
["Isaiah 44:3","He will send the Spirit of God","Pošle Božieho Ducha","John 16:7, 13"],
["Isaiah 45:21–25","He is Lord and Saviour","Je Pán a Spasiteľ","Philippians 3:20; Titus 2:13"],
["Isaiah 45:23","He will be the Judge","Bude Sudcom","John 5:22; Romans 14:11"],
["Isaiah 46:9–10","Declares things not yet done","Oznamuje veci, ktoré sa ešte nestali","John 13:19"],
["Isaiah 48:12","The First and the Last","Prvý a Posledný","John 1:30; Revelation 1:8, 17"],
["Isaiah 48:16–17","He came as a Teacher","Prišiel ako Učiteľ","John 3:2"],
["Isaiah 49:1","Called from the womb — His humanity","Povolaný od lona matky — jeho ľudskosť","Matthew 1:18"],
["Isaiah 49:5","A Servant from the womb","Služobník od lona matky","Luke 1:31; Philippians 2:7"],
["Isaiah 49:6","He will restore Israel","Obnoví Izrael","Acts 3:19–21; 15:16–17"],
["Isaiah 49:6","He is salvation for Israel","Je spásou pre Izrael","Luke 2:29–32"],
["Isaiah 49:6","He is the Light of the Gentiles","Je Svetlom pohanov","John 8:12; Acts 13:47"],
["Isaiah 49:6","Salvation unto the ends of the earth","Spása až po končiny zeme","Acts 15:7–18"],
["Isaiah 49:7","He is despised of the nation","Národ ním pohŕda","John 1:11; 8:48–49; 19:14–15"],
["Isaiah 50:3","Heaven clothed in black at His humiliation","Nebo sa odelo do čierneho pri jeho ponížení","Luke 23:44–45"],
["Isaiah 50:4","A learned counsellor for the weary","Učený radca pre unavených","Matthew 7:29; 11:28–29"],
["Isaiah 50:5","The Servant bound willingly to obedience","Služobník dobrovoľne poslušný","Matthew 26:39"],
["Isaiah 50:6","“I gave my back to the smiters.”","„Chrbát som nastavil tým, čo bili.“","Matthew 27:26"],
["Isaiah 50:6","He was smitten on the cheeks","Bili ho po lícach","Matthew 26:67"],
["Isaiah 50:6","He was spat upon","Pľuli na neho","Matthew 27:30"],
["Isaiah 52:7","Published good tidings upon the mountains","Hlásal dobrú zvesť na vrchoch","Matthew 5:12; 15:29; 28:16"],
["Isaiah 52:13","The Servant exalted","Služobník vyvýšený","Acts 1:8–11; Ephesians 1:19–22"],
["Isaiah 52:14","The Servant shockingly abused","Služobník strašne znetvorený","Luke 18:31–34; Matthew 26:67–68"],
["Isaiah 52:15","Nations startled by the message of the Servant","Národy užasnú nad zvesťou o Služobníkovi","Romans 15:18–21"],
["Isaiah 52:15","His blood shed to make atonement for all","Jeho krv vyliata na zmierenie za všetkých","Revelation 1:5; Hebrews 9:13–14"],
["Isaiah 53:1","His people would not believe Him","Jeho ľud mu neuverí","John 12:37–38"],
["Isaiah 53:2","He grew up as a tender plant in a dry ground","Vyrástol ako výhonok zo suchej zeme","Luke 2:40, 52"],
["Isaiah 53:2","Appearance of an ordinary man","Výzor obyčajného človeka","Philippians 2:6–8"],
["Isaiah 53:3","Despised","Opovrhnutý","Luke 4:28–29"],
["Isaiah 53:3","Rejected","Odmietnutý","Matthew 27:21–23"],
["Isaiah 53:3","Great sorrow and grief","Veľký žiaľ a bolesť","Matthew 26:37–38; Luke 19:41"],
["Isaiah 53:3","Men hide from being associated with Him","Ľudia sa skrývajú, aby s ním neboli spájaní","Mark 14:50–52"],
["Isaiah 53:4","He would have a healing ministry","Služba uzdravovania","Matthew 8:16–17"],
["Isaiah 53:4","Thought to be cursed by God","Pokladaný za prekliateho Bohom","Matthew 26:66; 27:41–43"],
["Isaiah 53:5","Bears the penalty for mankind's iniquities","Nesie trest za neprávosti ľudstva","2 Corinthians 5:21; Hebrews 2:9"],
["Isaiah 53:5","His sacrifice provides peace between man and God","Jeho obeta prináša pokoj medzi človekom a Bohom","Colossians 1:20"],
["Isaiah 53:5","His sacrifice would heal man of sin","Jeho obeta uzdravuje človeka z hriechu","1 Peter 2:24"],
["Isaiah 53:6","He would be the sin-bearer for all mankind","Nositeľ hriechu za celé ľudstvo","1 John 2:2; 4:10"],
["Isaiah 53:6","God's will that He bear sin for all mankind","Božia vôľa, aby niesol hriech za všetkých","Galatians 1:4"],
["Isaiah 53:7","Oppressed and afflicted","Utláčaný a trápený","Matthew 27:27–31"],
["Isaiah 53:7","Silent before His accusers","Mlčal pred žalobcami","Matthew 27:12–14"],
["Isaiah 53:7","Sacrificial lamb","Obetný baránok","John 1:29; 1 Peter 1:18–19"],
["Isaiah 53:8","Confined and persecuted","Zajatý a prenasledovaný","Matthew 26:47–75; 27:1–31"],
["Isaiah 53:8","He would be judged","Bol súdený","John 18:13–22"],
["Isaiah 53:8","Killed","Zabitý","Matthew 27:35"],
["Isaiah 53:8","Dies for the sins of the world","Zomiera za hriechy sveta","1 John 2:2"],
["Isaiah 53:9","Buried in a rich man's grave","Pochovaný v hrobe boháča","Matthew 27:57–60"],
["Isaiah 53:9","Innocent — had done no violence","Nevinný — nedopustil sa násilia","Luke 23:41; John 18:38"],
["Isaiah 53:9","No deceit in His mouth","V jeho ústach nebolo lesti","1 Peter 2:22"],
["Isaiah 53:10","God's will that He die for mankind","Božia vôľa, aby zomrel za ľudstvo","John 18:11"],
["Isaiah 53:10","An offering for sin","Obeta za hriech","Matthew 20:28; Galatians 3:13"],
["Isaiah 53:10","Resurrected — to live forever","Vzkriesený — žije naveky","Romans 6:9"],
["Isaiah 53:10","He would prosper","Pánova vôľa sa ním uskutoční","John 17:1–5"],
["Isaiah 53:11","God fully satisfied with His suffering","Boh plne uspokojený jeho utrpením","John 12:27"],
["Isaiah 53:11","God's Servant would justify man","Boží Služobník ospravedlní človeka","Romans 5:8–9, 18–19"],
["Isaiah 53:11","The sin-bearer for all mankind","Nositeľ hriechu za celé ľudstvo","Hebrews 9:28"],
["Isaiah 53:12","Exalted by God because of His sacrifice","Vyvýšený Bohom pre svoju obetu","Matthew 28:18"],
["Isaiah 53:12","He would give up His life to save mankind","Vydal svoj život na záchranu ľudstva","Luke 23:46"],
["Isaiah 53:12","Numbered with the transgressors","Počítaný medzi zločincov","Mark 15:27–28; Luke 22:37"],
["Isaiah 53:12","Bore the sin of many","Niesol hriech mnohých","1 Peter 2:24"],
["Isaiah 53:12","Intercedes to God on behalf of mankind","Prihovára sa u Boha za ľudstvo","Luke 23:34; Romans 8:34"],
["Isaiah 55:3","Resurrected by God","Vzkriesený Bohom","Acts 13:34"],
["Isaiah 55:4","A witness","Svedok","John 18:37"],
["Isaiah 55:4","He is a leader and commander","Vodca a vojvodca národov","Hebrews 2:10"],
["Isaiah 55:5","God would glorify Him","Boh ho oslávi","Acts 3:13"],
["Isaiah 59:16","Intercessor between man and God","Prímluvca medzi človekom a Bohom","Matthew 10:32"],
["Isaiah 59:16","He would come to provide salvation","Príde priniesť spásu","John 6:40"],
["Isaiah 59:20","He would come to Zion as their Redeemer","Príde na Sion ako Vykupiteľ","Luke 2:38"],
["Isaiah 60:1–3","He would show light to the Gentiles","Ukáže svetlo pohanom","Acts 26:23"],
["Isaiah 61:1","The Spirit of God upon Him","Boží Duch na ňom","Matthew 3:16–17"],
["Isaiah 61:1","The Messiah would preach the good news","Mesiáš bude hlásať dobrú zvesť","Luke 4:16–21"],
["Isaiah 61:1","Freedom from the bondage of sin","Sloboda z otroctva hriechu","John 8:31–36"],
["Isaiah 61:1–2","To proclaim a period of grace","Vyhlási čas milosti","Galatians 4:4–5"]
]],
["Jeremiah", [
["Jeremiah 23:5–6","Descendant of David","Potomok Dávida","Luke 3:23–31"],
["Jeremiah 23:5–6","The Messiah would be both God and man","Mesiáš bude Boh i človek","John 13:13; 1 Timothy 3:16"],
["Jeremiah 31:15","Massacre of infants at His birth","Vraždenie neviniatok pri jeho narodení","Matthew 2:16–18"],
["Jeremiah 31:22","Born of a virgin","Narodený z panny","Matthew 1:18–20"],
["Jeremiah 31:31","The Messiah would be the new covenant","Mesiáš bude novou zmluvou","Matthew 26:28"],
["Jeremiah 33:14–15","Descendant of David","Potomok Dávida","Luke 3:23–31"]
]],
["Ezekiel", [
["Ezekiel 34:23–24","Descendant of David — the one Shepherd","Potomok Dávida — jediný Pastier","Matthew 1:1; John 10:11"],
["Ezekiel 37:24–25","Descendant of David — king forever","Potomok Dávida — kráľ naveky","Luke 1:31–33"]
]],
["Daniel", [
["Daniel 2:44–45","The Stone that shall break the kingdoms","Kameň, ktorý rozdrví kráľovstvá","Matthew 21:44"],
["Daniel 7:13–14","He would ascend into heaven","Vystúpi do neba","Acts 1:9–11"],
["Daniel 7:13–14","Highly exalted","Vysoko vyvýšený","Ephesians 1:20–22"],
["Daniel 7:13–14","His dominion would be everlasting","Jeho vláda bude večná","Luke 1:31–33"],
["Daniel 9:24","To make an end to sins","Skoncuje s hriechom","Galatians 1:3–5"],
["Daniel 9:24","To make reconciliation for iniquity","Vykoná zmierenie za neprávosť","Romans 5:10; 2 Corinthians 5:18–21"],
["Daniel 9:24","He would be holy","Bude svätý","Luke 1:35"],
["Daniel 9:25","His announcement — the time of His coming","Ohlásenie — čas jeho príchodu","John 12:12–13"],
["Daniel 9:26","Cut off","Bude vyťatý — zabitý","Matthew 16:21; 21:38–39"],
["Daniel 9:26","To die for the sins of the world","Zomrie za hriechy sveta","Hebrews 2:9"],
["Daniel 9:26","Killed before the destruction of the Temple","Zabitý pred zničením chrámu","Matthew 27:50–51"]
]],
["Minor Prophets", [
["Hosea 11:1","He would be called out of Egypt","Povolaný z Egypta","Matthew 2:15"],
["Hosea 13:14","He would defeat death","Porazí smrť","1 Corinthians 15:55–57"],
["Joel 2:28","The promise of the Spirit","Prisľúbenie Ducha","Acts 2:17–21"],
["Joel 2:32","To offer salvation to all mankind","Ponúkne spásu celému ľudstvu","Romans 10:9–13"],
["Jonah 1:17","Three days and nights in the grave","Tri dni a tri noci v hrobe","Matthew 12:40; 16:4"],
["Micah 5:2","Born in Bethlehem","Narodený v Betleheme","Matthew 2:1–6"],
["Micah 5:2","Ruler in Israel","Vládca v Izraeli","Luke 1:33"],
["Micah 5:2","From everlasting","Od večnosti","John 8:58"],
["Haggai 2:6–9","He would visit the second Temple","Navštívi druhý chrám","Luke 2:27–32"],
["Haggai 2:23","Descendant of Zerubbabel","Potomok Zorobábela","Luke 3:26–27"],
["Amos 8:9","Darkness over the land at midday","Tma nad krajinou napoludnie","Matthew 27:45; Mark 15:33"]
]],
["Zechariah", [
["Zechariah 3:8","God's Servant — the Branch","Boží služobník — Výhonok","John 17:4"],
["Zechariah 6:12–13","Priest and King","Kňaz i Kráľ","Hebrews 8:1"],
["Zechariah 9:9","Greeted with rejoicing in Jerusalem","Vítaný s jasotom v Jeruzaleme","Matthew 21:8–10"],
["Zechariah 9:9","Beheld as King","Videný ako Kráľ","John 12:12–13"],
["Zechariah 9:9","The Messiah would be just","Mesiáš bude spravodlivý","John 5:30"],
["Zechariah 9:9","The Messiah would bring salvation","Mesiáš prinesie spásu","Luke 19:10"],
["Zechariah 9:9","The Messiah would be humble","Mesiáš bude pokorný","Matthew 11:29"],
["Zechariah 9:9","Presented to Jerusalem riding on a donkey","Vchádza do Jeruzalema na oslovi","Matthew 21:6–9"],
["Zechariah 10:4","The cornerstone","Uholný kameň","Ephesians 2:20"],
["Zechariah 11:4–6","At His coming Israel to have unfit leaders","Pri jeho príchode má Izrael nehodných vodcov","Matthew 23:1–4"],
["Zechariah 11:4–6","Rejection causes God to remove His protection","Odmietnutie spôsobí odňatie Božej ochrany","Luke 19:41–44"],
["Zechariah 11:4–6","Rejected in favour of another king","Odmietnutý v prospech iného kráľa","John 19:13–15"],
["Zechariah 11:7","Ministry to the poor — the believing remnant","Služba chudobným — veriacemu zvyšku","Matthew 9:35–36"],
["Zechariah 11:8","Unbelief forces Messiah to reject them","Nevera núti Mesiáša odmietnuť ich","Matthew 23:33"],
["Zechariah 11:8","Despised","Opovrhnutý","Matthew 27:20"],
["Zechariah 11:9","Stops ministering to those who rejected Him","Prestáva slúžiť tým, ktorí ho odmietli","Matthew 13:10–11"],
["Zechariah 11:10–11","The believing remnant recognise God's word","Veriaci zvyšok spoznáva Božie slovo","Luke 19:41–44"],
["Zechariah 11:10–11","The Messiah would be God","Mesiáš bude Boh","John 14:7"],
["Zechariah 11:12–13","Betrayed for thirty pieces of silver","Zradený za tridsať strieborných","Matthew 26:14–15"],
["Zechariah 11:12–13","Priced at a slave's wage","Ocenený mzdou otroka","Matthew 26:14–15"],
["Zechariah 11:12–13","The silver cast into the house of the Lord","Striebro hodené v Pánovom dome","Matthew 27:3–5"],
["Zechariah 11:12–13","The price paid for the potter's field","Cena zaplatená za hrnčiarovo pole","Matthew 27:6–10"],
["Zechariah 12:10","The Messiah's body would be pierced","Mesiášovo telo bude prebodnuté","John 19:34–37"],
["Zechariah 12:10","The Messiah would be both God and man","Mesiáš bude Boh i človek","John 10:30"],
["Zechariah 12:10","The Messiah would be rejected","Mesiáš bude odmietnutý","John 1:11"],
["Zechariah 13:7","God's will that He die for mankind","Božia vôľa, aby zomrel za ľudstvo","John 18:11"],
["Zechariah 13:7","A violent death","Násilná smrť","Mark 14:27"],
["Zechariah 13:7","Both God and man","Boh i človek","John 14:9"],
["Zechariah 13:7","Israel scattered as a result of rejecting Him","Ovce sa rozpŕchnu — učeníci sa rozutekajú","Matthew 26:31–56"]
]],
["Malachi", [
["Malachi 3:1","Messenger to prepare the way for Messiah","Posol pripraví cestu Mesiášovi","Matthew 11:10"],
["Malachi 3:1","Sudden appearance at the Temple","Náhle príde do chrámu","Mark 11:15–16"],
["Malachi 3:1","Messenger of the new covenant","Posol novej zmluvy","Luke 4:43"],
["Malachi 4:5","Forerunner in the spirit of Elijah","Predchodca v duchu Eliáša","Matthew 3:1–3; 11:10–14; 17:11–13"],
["Malachi 4:6","Forerunner would turn many to righteousness","Predchodca obráti mnohých k spravodlivosti","Luke 1:16–17"]
]]
];
